//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int TimeTableId { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
        public int SubjectOrder { get; set; }
    }
}
